name: Continuous Integration
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker login
      run: docker login -u twinsnes -p ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build a Docker image
      run: docker build -t twinsnes/cf-rmit-app:${{ github.run_number }} ./app

    # - name: Run Snyk to check Docker image for vulnerabilities
    #   uses: snyk/actions/docker@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     image: twinsnes/cf-rmit-app:${{ github.run_number }}
    #     args: --file=app/Dockerfile

    # - name: Upload result to GitHub Code Scanning 
    #   if: failure()
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: snyk.sarif

    - name: Publish Docker image
      run: docker push twinsnes/cf-rmit-app:${{ github.run_number }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: update manifests
      run: |
        cd manifests/overlay/test
        kustomize edit set image twinsnes/cf-rmit-app=twinsnes/cf-rmit-app:${{ github.run_number }}

    - name: Commit manifest changes
      run: |
        git config --global user.name 'GH Action'
        git config --global user.email 'gh-action@users.noreply.github.com'
        git add manifests
        git commit -m "Updated Image in Manifest"
        git push