name: Continuous Integration
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u twinsnes -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build a Docker image
      run: docker build -t twinsnes/cf-rmit-app:${{ github.run_number }} ./app
    # - name: Run Snyk to check Docker image for vulnerabilities
    #   uses: snyk/actions/docker@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   with:
    #     image: twinsnes/cf-rmit-app:${{ github.run_number }}
    #     args: --file=app/Dockerfile
    # - name: Upload result to GitHub Code Scanning 
    #   if: failure()
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: snyk.sarif
    - name: Publish Docker image
      run: docker push twinsnes/cf-rmit-app:${{ github.run_number }}
    - name: report image to Codefresh
      uses: codefresh-io/codefresh-report-image@latest
      with:
        CF_RUNTIME_NAME: 'codefresh-hosted'
        CF_API_KEY: ${{ secrets.CF_TOKEN}}
        CF_IMAGE: twinsnes/cf-rmit-app:${{ github.run_number }}
        CF_GIT_BRANCH: 'main'
        CF_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}